car: 
  T_bc:
    - [1, 0, 0, 0]
    - [0, 1, 0, 0]
    - [0, 0, 1, 0]
    - [0, 0, 0, 1]
  params:
    l: 3.0
    dt: 0.1
    v: 30
    delta: -0.1
  simulation:
    n_points: 15
    n_frames: 15
  noise:
    apply: true
    pose_noise: 0.1
    point_noise: 0.1

cam:
  calibration:
    - [707.0912,        0, 601.8873]
    - [       0, 707.0912, 183.1104]
    - [       0,        0,        1]
  image_dims:
    heigh: 376
    width: 1241
  T_bc:
    - [1, 0, 0, 0]
    - [0, 0, 1, 0]
    - [0,-1, 0, 0]
    - [0, 0, 0, 1]
  simulation:
    n_points: 40
    n_frames: 15
    n_obs: 3
  noise:
    apply: true
    obs_noise: 0.1
    pose_noise: 0.1
    point_noise: 0.1

use_dynamic_points: true